apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./deployment.yaml
  - ./role.yaml
  - ./role_binding.yaml
  - ./service_account.yaml
  - ./spinnaker.io_spinnakerservices_crd.yaml
