apiVersion: apps/v1
kind: Deployment
metadata:
  name: armory-agent
spec:
  selector:
    matchLabels:
      app: armory-agent
      cluster: armory-agent
  template:
    spec:
      containers:
      - name: armory-agent
        volumeMounts:
        - mountPath: /opt/armory/config
          name: volume-agent-config
      volumes:
      - name: volume-agent-config
        configMap:
          name: agent-config
